#!/usr/bin/env python3
"""Validate nilamp's native CLAP shell through REAPER."""
from __future__ import annotations

import argparse
import math
import os
import shutil
import struct
import subprocess
import sys
import time
import wave
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]
LUA_DRIVER = HERE / "validate_reaper_clap.lua"
LUA_CFG_PATH = Path("/tmp/nilamp_clap_validate_cfg.lua")
DRIVER_LOG = Path("/tmp/nilamp_clap_validate.log")
REAPER_LOG = Path("/tmp/nilamp_clap_validate.reaper.log")

EXPECTED_PARAMS = ["Gain", "Volume", "Bass", "Mid", "Treble", "Sag"]
PLUGIN_CANDIDATES = [
    "CLAP: nilamp TWD MKII (niltempus)",
    "nilamp TWD MKII (niltempus)",
    "nilamp TWD MKII",
    "dev.niltempus.nilamp",
]


def lua_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_input_wav(path: Path, sample_rate: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    frames = sample_rate
    with wave.open(str(path), "wb") as wav:
        wav.setnchannels(2)
        wav.setsampwidth(2)
        wav.setframerate(sample_rate)
        data = bytearray()
        for i in range(frames):
            t = i / sample_rate
            left = int(0.15 * 32767.0 * math.sin(2.0 * math.pi * 220.0 * t))
            right = int(0.10 * 32767.0 * math.sin(2.0 * math.pi * 330.0 * t))
            data.extend(struct.pack("<hh", left, right))
        wav.writeframes(bytes(data))


def write_temp_project(path: Path) -> None:
    path.write_text("<REAPER_PROJECT 0.1 \"7.0\" 1710000000\n>\n")


def write_lua_cfg(*, input_wav: Path, output_wav: Path, log_path: Path, sample_rate: int) -> None:
    lines = [
        "-- Auto-generated by tools/clap_validate/validate_reaper_clap.py; do not hand-edit.",
        "return {",
        f"  input = {lua_str(str(input_wav))},",
        f"  output = {lua_str(str(output_wav))},",
        f"  log = {lua_str(str(log_path))},",
        f"  sr = {sample_rate},",
        "  plugin_candidates = {",
    ]
    for candidate in PLUGIN_CANDIDATES:
        lines.append(f"    {lua_str(candidate)},")
    lines.extend([
        "  },",
        "  expected_params = {",
    ])
    for name in EXPECTED_PARAMS:
        lines.append(f"    {lua_str(name)},")
    lines.extend([
        "  },",
        "  params = {",
        "    { index = 0, value = 6.0 },",
        "    { index = 1, value = 80.0 },",
        "    { index = 2, value = 30.0 },",
        "    { index = 3, value = 60.0 },",
        "    { index = 4, value = 70.0 },",
        "    { index = 5, value = 100.0 },",
        "  },",
        "}",
    ])
    LUA_CFG_PATH.write_text("\n".join(lines) + "\n")


def read_chunks(path: Path) -> tuple[bytes, bytes]:
    data = path.read_bytes()
    if len(data) < 12 or data[:4] != b"RIFF" or data[8:12] != b"WAVE":
        raise RuntimeError(f"not a RIFF/WAVE file: {path}")
    pos = 12
    fmt = None
    samples = None
    while pos + 8 <= len(data):
        chunk_id = data[pos:pos + 4]
        size = struct.unpack_from("<I", data, pos + 4)[0]
        start = pos + 8
        end = start + size
        if end > len(data):
            raise RuntimeError(f"truncated WAV chunk {chunk_id!r}")
        if chunk_id == b"fmt ":
            fmt = data[start:end]
        elif chunk_id == b"data":
            samples = data[start:end]
        pos = end + (size & 1)
    if fmt is None or samples is None:
        raise RuntimeError("missing fmt or data chunk in render")
    return fmt, samples


def wav_peak(path: Path) -> float:
    fmt, data = read_chunks(path)
    if len(fmt) < 16:
        raise RuntimeError("short WAV fmt chunk")
    tag, channels, _sr, _byte_rate, block_align, bits = struct.unpack_from("<HHIIHH", fmt, 0)
    if channels == 0 or block_align == 0 or bits == 0:
        raise RuntimeError("invalid WAV format")
    if len(data) < block_align:
        raise RuntimeError("render has no samples")

    peak = 0.0
    if tag == 1:
        bytes_per_sample = bits // 8
        if bytes_per_sample == 0:
            raise RuntimeError("invalid PCM sample width")
        for offset in range(0, len(data) - bytes_per_sample + 1, bytes_per_sample):
            raw = data[offset:offset + bytes_per_sample]
            if bytes_per_sample == 1:
                value = (raw[0] - 128) / 128.0
            else:
                signed = int.from_bytes(raw, "little", signed=True)
                value = signed / float(1 << (bits - 1))
            peak = max(peak, abs(value))
    elif tag == 3 and bits == 32:
        for (value,) in struct.iter_unpack("<f", data[:len(data) - (len(data) % 4)]):
            if not math.isfinite(value):
                raise RuntimeError("render contains non-finite float sample")
            peak = max(peak, abs(value))
    elif tag == 3 and bits == 64:
        for (value,) in struct.iter_unpack("<d", data[:len(data) - (len(data) % 8)]):
            if not math.isfinite(value):
                raise RuntimeError("render contains non-finite float sample")
            peak = max(peak, abs(value))
    else:
        raise RuntimeError(f"unsupported WAV format tag={tag} bits={bits}")
    return peak


def run_optional_clap_validator(plugin: Path) -> None:
    validator = shutil.which("clap-validator")
    if not validator:
        print("clap-validator not found; skipping external CLAP validation")
        return

    proc = subprocess.run(
        [validator, "validate", str(plugin)],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    if proc.stdout:
        print(proc.stdout, end="")
    if proc.returncode != 0:
        raise RuntimeError(f"clap-validator failed with exit code {proc.returncode}")


def run_reaper(*, reaper_bin: str, plugin: Path, output_wav: Path, timeout_s: float,
               max_peak: float) -> None:
    for path in (output_wav, DRIVER_LOG, REAPER_LOG, LUA_CFG_PATH):
        try:
            path.unlink()
        except FileNotFoundError:
            pass

    input_wav = output_wav.with_name("nilamp_clap_validate_input.wav")
    project_path = output_wav.with_name("nilamp_clap_validate_project.RPP")
    sample_rate = 48000
    write_input_wav(input_wav, sample_rate)
    write_temp_project(project_path)
    write_lua_cfg(input_wav=input_wav, output_wav=output_wav,
                  log_path=DRIVER_LOG, sample_rate=sample_rate)

    env = os.environ.copy()
    plugin_dir = str(plugin.resolve().parent)
    env["CLAP_PATH"] = plugin_dir if not env.get("CLAP_PATH") else plugin_dir + os.pathsep + env["CLAP_PATH"]

    with REAPER_LOG.open("wb") as logf:
        proc = subprocess.Popen(
            [reaper_bin, "-newinst", "-nosplash", str(project_path), str(LUA_DRIVER)],
            stdout=logf,
            stderr=subprocess.STDOUT,
            env=env,
        )

    deadline = time.monotonic() + timeout_s
    last_size = -1
    stable_for = 0.0
    while time.monotonic() < deadline:
        time.sleep(0.5)
        if output_wav.exists():
            size = output_wav.stat().st_size
            if size == last_size and size > 0:
                stable_for += 0.5
                if stable_for >= 1.0:
                    break
            else:
                stable_for = 0.0
                last_size = size
        if proc.poll() is not None and not output_wav.exists():
            break

    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()
        proc.wait(timeout=5)
        raise RuntimeError(f"REAPER timed out; see {REAPER_LOG} and {DRIVER_LOG}")

    driver_text = DRIVER_LOG.read_text(errors="replace") if DRIVER_LOG.exists() else ""
    if "FATAL:" in driver_text:
        raise RuntimeError(f"REAPER driver reported failure; see {DRIVER_LOG}")
    if proc.returncode != 0:
        raise RuntimeError(f"REAPER exited with {proc.returncode}; see {REAPER_LOG}")
    if not output_wav.exists():
        raise RuntimeError(f"REAPER did not produce output; see {REAPER_LOG} and {DRIVER_LOG}")

    peak = wav_peak(output_wav)
    if peak <= 1.0e-8:
        raise RuntimeError(f"render is silent or near-silent: peak={peak:.6e}")
    if peak > max_peak:
        raise RuntimeError(f"render peak exceeds safety limit: peak={peak:.6e} max={max_peak:.6e}")
    print(f"REAPER CLAP render peak={peak:.6e}")


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plugin", default=REPO_ROOT / "native/bin/nilamp-twd-mkii.clap", type=Path)
    parser.add_argument("--output", default=Path("/tmp/nilamp_clap_validate/output.wav"), type=Path)
    parser.add_argument("--reaper-bin", default="reaper")
    parser.add_argument("--timeout", default=90.0, type=float)
    parser.add_argument("--max-peak", default=1.000001, type=float)
    parser.add_argument("--skip-clap-validator", action="store_true")
    args = parser.parse_args(argv)

    plugin = args.plugin.resolve()
    if not plugin.exists():
        raise FileNotFoundError(f"plugin not found: {plugin}")
    args.output.parent.mkdir(parents=True, exist_ok=True)

    if not args.skip_clap_validator:
        run_optional_clap_validator(plugin)
    run_reaper(reaper_bin=args.reaper_bin, plugin=plugin,
               output_wav=args.output.resolve(), timeout_s=args.timeout,
               max_peak=args.max_peak)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
