"""Render audio through Keller's TWD DLX II JSFX via REAPER's ReaScript.

Usage:
    from tools.jsfx_render.render_jsfx import render, slider_info
    out = render(
        input_wav="/tmp/in.wav",
        output_wav="/tmp/out.wav",
        sliders={"gin": 12, "vol": 80, "bass": 50, "mid": 50, "treble": 50},
        sample_rate=48000,
    )

Mechanism:
    - Parses slider declarations from the staged JSFX source
      (~/.config/REAPER/Effects/nilamp_abx/twd_dlx_ii.jsfx).
    - Emits a Lua config table at /tmp/render_jsfx_cfg.lua.
    - Invokes `reaper -nosplash <render_jsfx.lua>`.
    - Polls for the output file and returns its path.

Notes:
    - Requires `reaper` on PATH. Headless via JACK + an active X display.
    - JSFX must be staged at ~/.config/REAPER/Effects/nilamp_abx/.
    - Renders 32-bit float WAV.
    - Alternate staged JSFX effects can be selected with effect_name/jsfx_source.
"""
from __future__ import annotations

import os
import re
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Mapping

HERE = Path(__file__).resolve().parent
LUA_DRIVER = HERE / "render_jsfx.lua"
LUA_CFG_PATH = Path("/tmp/render_jsfx_cfg.lua")
DRIVER_LOG = Path("/tmp/render_jsfx.log")
REAPER_LOG = Path("/tmp/render_jsfx.reaper.log")

# Default location of staged JSFX bundle. Used only for slider parsing; the
# renderer references the JSFX by its REAPER-relative effect name.
DEFAULT_JSFX_SOURCE = (
    Path.home() / ".config" / "REAPER" / "Effects" / "nilamp_abx" / "twd_dlx_ii_harness.jsfx"
)
DEFAULT_EFFECT_NAME = "nilamp_abx/twd_dlx_ii_harness"


@dataclass(frozen=True)
class SliderInfo:
    index: int       # 1-based JSFX slider number; REAPER param index = index - 1
    name: str        # short name, e.g. "gin", "vol"
    default: float
    minimum: float
    maximum: float
    label: str       # human-readable label from the JSFX source


# Match e.g. `slider3:p.vol=  50  <0, 100, 2.5>-  Volume (%)`
# Capture: index, name (after `p.`), default, min, max, label.
_SLIDER_RE = re.compile(
    r"^slider(?P<idx>\d+)\s*:\s*p\.(?P<name>[A-Za-z0-9_]+)\s*=\s*"
    r"(?P<default>-?[\d.]+)\s*"
    r"<\s*(?P<min>-?[\d.]+)\s*,\s*(?P<max>-?[\d.]+)\s*,"
    r"[^>]*>\s*-?\s*(?P<label>.*?)\s*$",
    re.MULTILINE,
)


def parse_sliders(jsfx_path: Path = DEFAULT_JSFX_SOURCE) -> dict[str, SliderInfo]:
    """Parse `slider<N>:p.<name>=<default> <min,max,step>-label` declarations."""
    if not jsfx_path.exists():
        raise FileNotFoundError(f"JSFX source not found at {jsfx_path}")
    src = jsfx_path.read_text()
    out: dict[str, SliderInfo] = {}
    for m in _SLIDER_RE.finditer(src):
        info = SliderInfo(
            index=int(m["idx"]),
            name=m["name"],
            default=float(m["default"]),
            minimum=float(m["min"]),
            maximum=float(m["max"]),
            label=m["label"].strip(),
        )
        out[info.name] = info
    if not out:
        raise RuntimeError(f"No sliders parsed from {jsfx_path}")
    return out


def slider_info(jsfx_path: Path = DEFAULT_JSFX_SOURCE) -> dict[str, SliderInfo]:
    """Cached slider table."""
    global _SLIDER_CACHE
    key = Path(jsfx_path).resolve()
    try:
        return _SLIDER_CACHE[key]  # type: ignore[name-defined]
    except NameError:
        _SLIDER_CACHE = {}  # noqa: F841
    except KeyError:
        pass
    _SLIDER_CACHE[key] = parse_sliders(key)  # type: ignore[name-defined]
    return _SLIDER_CACHE[key]  # type: ignore[name-defined]


def _format_lua_value(v: float | int) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    return repr(float(v))


def _write_cfg(
    *,
    input_wav: Path,
    output_wav: Path,
    effect_name: str,
    sliders: list[tuple[int, float]],
    sample_rate: int,
    channels: int,
) -> None:
    lines = [
        "-- Auto-generated by tools/jsfx_render/render_jsfx.py; do not hand-edit.",
        "return {",
        f"  input  = {_lua_str(str(input_wav))},",
        f"  output = {_lua_str(str(output_wav))},",
        f"  effect = {_lua_str(effect_name)},",
        f"  sr     = {int(sample_rate)},",
        f"  channels = {int(channels)},",
        "  sliders = {",
    ]
    for idx, val in sliders:
        lines.append(f"    {{index={idx}, value={_format_lua_value(val)}}},")
    lines.append("  },")
    lines.append("}")
    LUA_CFG_PATH.write_text("\n".join(lines) + "\n")


def _lua_str(s: str) -> str:
    """Escape a Python string as a Lua double-quoted literal."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _write_temp_project(path: Path) -> None:
    path.write_text("<REAPER_PROJECT 0.1 \"7.0\" 1710000000\n>\n")


def render(
    *,
    input_wav: str | os.PathLike[str],
    output_wav: str | os.PathLike[str],
    sliders: Mapping[str, float] | None = None,
    sample_rate: int = 48000,
    reaper_bin: str = "reaper",
    timeout_s: float = 60.0,
    poll_interval_s: float = 0.5,
    effect_name: str = DEFAULT_EFFECT_NAME,
    jsfx_source: str | os.PathLike[str] = DEFAULT_JSFX_SOURCE,
    channels: int = 1,
) -> Path:
    """Render `input_wav` through TWD DLX II JSFX, write to `output_wav`.

    Sliders are passed by short name (e.g. "gin", "vol"); unspecified sliders
    use their JSFX defaults. Returns the absolute output path.
    """
    input_path = Path(input_wav).resolve()
    output_path = Path(output_wav).resolve()
    if not input_path.is_file():
        raise FileNotFoundError(f"input wav not found: {input_path}")
    if channels < 1:
        raise ValueError("channels must be >= 1")
    output_path.parent.mkdir(parents=True, exist_ok=True)

    info = slider_info(Path(jsfx_source))
    requested = dict(sliders or {})
    unknown = set(requested) - set(info)
    if unknown:
        raise ValueError(
            f"Unknown slider(s): {sorted(unknown)}. "
            f"Known: {sorted(info)}"
        )

    # Build (1-based-index, value) pairs only for explicitly-set sliders.
    # Unset sliders keep their JSFX-declared defaults.
    pairs: list[tuple[int, float]] = []
    for name, value in requested.items():
        si = info[name]
        if not (si.minimum <= float(value) <= si.maximum):
            raise ValueError(
                f"slider '{name}' = {value} out of range "
                f"[{si.minimum}, {si.maximum}]"
            )
        pairs.append((si.index, float(value)))
    pairs.sort()

    # Clean stale artifacts so polling is unambiguous.
    for p in (output_path, DRIVER_LOG, REAPER_LOG):
        try:
            p.unlink()
        except FileNotFoundError:
            pass
    project_path = output_path.with_name(f"{output_path.stem}_render_project.RPP")
    _write_temp_project(project_path)

    _write_cfg(
        input_wav=input_path,
        output_wav=output_path,
        effect_name=effect_name,
        sliders=pairs,
        sample_rate=sample_rate,
        channels=channels,
    )

    # Launch REAPER. The Lua script self-quits via Main_OnCommand(40004),
    # but we also enforce a hard timeout via subprocess.
    with REAPER_LOG.open("wb") as logf:
        proc = subprocess.Popen(
            [reaper_bin, "-newinst", "-nosplash", str(project_path), str(LUA_DRIVER)],
            stdout=logf,
            stderr=subprocess.STDOUT,
        )

    try:
        deadline = time.monotonic() + timeout_s
        last_size = -1
        stable_for = 0.0
        while time.monotonic() < deadline:
            time.sleep(poll_interval_s)
            if output_path.exists():
                size = output_path.stat().st_size
                if size == last_size and size > 0:
                    stable_for += poll_interval_s
                    if stable_for >= 1.0:
                        break  # file stopped growing
                else:
                    stable_for = 0.0
                    last_size = size
            if proc.poll() is not None and not output_path.exists():
                # REAPER exited without producing output; fail fast.
                break
        else:
            raise TimeoutError(
                f"render timed out after {timeout_s}s "
                f"(see {REAPER_LOG} and {DRIVER_LOG})"
            )
    finally:
        if proc.poll() is None:
            proc.terminate()
            try:
                proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                proc.kill()

    if not output_path.exists() or output_path.stat().st_size == 0:
        log_tail = ""
        if DRIVER_LOG.exists():
            log_tail = DRIVER_LOG.read_text()[-2000:]
        raise RuntimeError(
            f"render produced no output at {output_path}.\n"
            f"--- driver log ---\n{log_tail}"
        )
    return output_path


def _cli() -> int:
    import argparse
    ap = argparse.ArgumentParser(description="Render audio through Keller TWD DLX II JSFX.")
    ap.add_argument("input_wav", nargs="?")
    ap.add_argument("output_wav", nargs="?")
    ap.add_argument(
        "--slider", "-s", action="append", default=[],
        help="NAME=VALUE; repeatable. e.g. -s gin=12 -s vol=80",
    )
    ap.add_argument("--sample-rate", type=int, default=48000)
    ap.add_argument("--timeout", type=float, default=60.0,
                    help="REAPER render timeout in seconds (default: 60)")
    ap.add_argument("--effect-name", default=DEFAULT_EFFECT_NAME,
                    help=f"REAPER JSFX effect name (default: {DEFAULT_EFFECT_NAME})")
    ap.add_argument("--jsfx-source", type=Path, default=DEFAULT_JSFX_SOURCE,
                    help="JSFX source path used for slider parsing.")
    ap.add_argument("--channels", type=int, default=1,
                    help="Render channel count (default: 1).")
    ap.add_argument("--list-sliders", action="store_true")
    args = ap.parse_args()

    if args.list_sliders:
        for name, si in sorted(slider_info(args.jsfx_source).items(), key=lambda kv: kv[1].index):
            print(f"  {si.index:>2}  {name:<10} default={si.default:<6} "
                  f"range=[{si.minimum}, {si.maximum}]  {si.label}")
        return 0

    if not args.input_wav or not args.output_wav:
        ap.error("input_wav and output_wav are required (unless --list-sliders)")

    sliders: dict[str, float] = {}
    for spec in args.slider:
        if "=" not in spec:
            raise SystemExit(f"bad --slider spec (need NAME=VALUE): {spec!r}")
        name, value = spec.split("=", 1)
        sliders[name.strip()] = float(value)

    out = render(
        input_wav=args.input_wav,
        output_wav=args.output_wav,
        sliders=sliders,
        sample_rate=args.sample_rate,
        timeout_s=args.timeout,
        effect_name=args.effect_name,
        jsfx_source=args.jsfx_source,
        channels=args.channels,
    )
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(_cli())
