-- SPDX-License-Identifier: MIT
-- Generate C arrays from dsp/5e3_tables.lib waveform definitions.

local input = assert(arg[1], "usage: gen_tables.lua dsp/5e3_tables.lib native/build")
local out_dir = assert(arg[2], "usage: gen_tables.lua dsp/5e3_tables.lib native/build")

local wanted = {
  "t1_12ax7_table",
  "t2_12ax7_table",
  "t3_cd_table",
  "t4_6v6_table",
  "t5_6v6_table",
}

local f = assert(io.open(input, "rb"))
local src = f:read("*a")
f:close()

local function sanitize(name)
  return name:gsub("[^A-Za-z0-9_]", "_")
end

local tables = {}
for _, name in ipairs(wanted) do
  local pattern = name .. "%s*=%s*waveform%s*{(.-)};"
  local body = src:match(pattern)
  assert(body, "missing waveform " .. name)
  local values = {}
  for num in body:gmatch("[+-]?%d+%.%d+e[+-]%d+") do
    values[#values + 1] = num
  end
  assert(#values > 0, "no numeric values for " .. name)
  tables[#tables + 1] = { name = name, symbol = "nilamp_" .. sanitize(name), values = values }
end

local h = assert(io.open(out_dir .. "/nilamp_tables.h", "wb"))
h:write("// SPDX-License-Identifier: MIT\n")
h:write("// Generated by native/scripts/gen_tables.lua. Do not edit.\n\n")
h:write("#ifndef NILAMP_TABLES_H\n#define NILAMP_TABLES_H\n\n")
h:write("#include <stddef.h>\n\n")
for _, tbl in ipairs(tables) do
  h:write(("extern const float %s[%d];\n"):format(tbl.symbol, #tbl.values))
  h:write(("extern const size_t %s_len;\n"):format(tbl.symbol))
end
h:write("\n#endif\n")
h:close()

local c = assert(io.open(out_dir .. "/nilamp_tables.c", "wb"))
c:write("// SPDX-License-Identifier: MIT\n")
c:write("// Generated by native/scripts/gen_tables.lua. Do not edit.\n\n")
c:write("#include \"nilamp_tables.h\"\n\n")
for _, tbl in ipairs(tables) do
  c:write(("const float %s[%d] = {\n"):format(tbl.symbol, #tbl.values))
  for i, value in ipairs(tbl.values) do
    if (i - 1) % 6 == 0 then
      c:write("    ")
    end
    c:write(value, "f")
    if i ~= #tbl.values then
      c:write(", ")
    end
    if i % 6 == 0 or i == #tbl.values then
      c:write("\n")
    end
  end
  c:write("};\n")
  c:write(("const size_t %s_len = %d;\n\n"):format(tbl.symbol, #tbl.values))
end
c:close()
