// SPDX-License-Identifier: MIT
//
// Per-stage regression tests against the Python oracle (tools/keller_oracle.py).
//
// Fixtures live in tests/fixtures/ as raw little-endian float32 buffers.
// They are generated by `python3 tools/gen_fixtures.py`; do not hand-edit.

mod common;

use common::*;

// ---------------------------------------------------------------------------
// PKD — peak detector
// ---------------------------------------------------------------------------
//
// Generated test DSP: dsp/tests/test_pkd.dsp (compiled by build.rs to
// $OUT_DIR/test_pkd.rs with the struct renamed to `test_pkd`).

mod test_pkd {
    #![allow(non_snake_case, non_camel_case_types, dead_code, unused_mut, unused_variables, unused_parens, clippy::all)]
    use super::*;
    include!(concat!(env!("OUT_DIR"), "/test_pkd.rs"));
}

#[test]
fn pkd_matches_oracle() {
    use test_pkd::test_pkd as Dsp;

    let sample_rate = 48_000;
    let input: Vec<f32> = read_f32_bin("tests/fixtures/sine_1k_amp05_48k_4800.f32");
    let expected: Vec<f32> = read_f32_bin("tests/fixtures/pkd_baseline_48k.f32");

    // Build param map by walking the DSP's static UI.
    let mut pmap = ParamMap::default();
    Dsp::build_user_interface_static(&mut pmap);

    let mut dsp = Dsp::new();
    dsp.init(sample_rate);
    dsp.instance_clear();

    // Match the oracle fixture parameters exactly:
    //   xth = 0.0, xdiode = 0.001
    //   k1 = 1 - exp(-1 / (1e-3 * sr))     (1 ms attack)
    //   k2 = exp(-1 / (50e-3 * sr))        (50 ms release)
    let k1 = 1.0 - (-1.0_f32 / (1e-3 * sample_rate as f32)).exp();
    let k2 = (-1.0_f32 / (50e-3 * sample_rate as f32)).exp();
    dsp.set_param(pmap.lookup("xth"), 0.0);
    dsp.set_param(pmap.lookup("xdiode"), 0.001);
    dsp.set_param(pmap.lookup("k1"), k1);
    dsp.set_param(pmap.lookup("k2"), k2);

    let n = input.len();
    let mut output = vec![0f32; n];

    // Faust expects slice-of-slice.  We pass a single block.
    let in_slice: &[f32] = &input;
    let out_slice: &mut [f32] = &mut output;
    let inputs: [&[f32]; 1] = [in_slice];
    let mut outputs: [&mut [f32]; 1] = [out_slice];
    dsp.compute(n, &inputs, &mut outputs);

    let report = compare(&output, &expected);
    println!(
        "[pkd] max_abs={:.3e}  rms={:.3e}  n={}",
        report.max_abs, report.rms, report.n
    );
    report.assert_within(1e-3, 1e-4, "pkd_matches_oracle");
}
