// SPDX-License-Identifier: MIT
//
// Per-stage regression tests against the Python oracle (tools/keller_oracle.py).
//
// Fixtures live in tests/fixtures/ as raw little-endian float32 buffers.
// They are generated by `python3 tools/gen_fixtures.py`; do not hand-edit.

mod common;

use common::*;

// ---------------------------------------------------------------------------
// PKD — peak detector
// ---------------------------------------------------------------------------
//
// Generated test DSP: dsp/tests/test_pkd.dsp (compiled by build.rs to
// $OUT_DIR/test_pkd.rs with the struct renamed to `test_pkd`).

mod test_pkd {
    #![allow(
        non_snake_case,
        non_camel_case_types,
        non_upper_case_globals,
        dead_code,
        unused_mut,
        unused_variables,
        unused_parens,
        clippy::all
    )]
    use super::*;
    include!(concat!(env!("OUT_DIR"), "/test_pkd.rs"));
}

#[test]
fn pkd_matches_oracle() {
    use test_pkd::test_pkd as Dsp;

    let sample_rate = 48_000;
    let input: Vec<f32> = read_f32_bin("tests/fixtures/sine_1k_amp05_48k_4800.f32");
    let expected: Vec<f32> = read_f32_bin("tests/fixtures/pkd_baseline_48k.f32");

    // Build param map by walking the DSP's static UI.
    let mut pmap = ParamMap::default();
    Dsp::build_user_interface_static(&mut pmap);

    let mut dsp = Dsp::new();
    dsp.init(sample_rate);
    dsp.instance_clear();

    // Match the oracle fixture parameters exactly:
    //   xth = 0.0, xdiode = 0.001
    //   k1 = 1 - exp(-1 / (1e-3 * sr))     (1 ms attack)
    //   k2 = exp(-1 / (50e-3 * sr))        (50 ms release)
    let k1 = 1.0 - (-1.0_f32 / (1e-3 * sample_rate as f32)).exp();
    let k2 = (-1.0_f32 / (50e-3 * sample_rate as f32)).exp();
    dsp.set_param(pmap.lookup("xth"), 0.0);
    dsp.set_param(pmap.lookup("xdiode"), 0.001);
    dsp.set_param(pmap.lookup("k1"), k1);
    dsp.set_param(pmap.lookup("k2"), k2);

    let output = run_siso(&mut dsp, &input);

    let report = compare(&output, &expected);
    println!(
        "[pkd] max_abs={:.3e}  rms={:.3e}  n={}",
        report.max_abs, report.rms, report.n
    );
    report.assert_within(1e-3, 1e-4, "pkd_matches_oracle");
}

// ---------------------------------------------------------------------------
// ADNL — waveshaper (ADAA) per-table regression
// ---------------------------------------------------------------------------
//
// One macro invocation per 5E3 GLF table (T1_12AX7, T2_12AX7, T3_CD,
// T4_6V6, T5_6V6).
// Each invocation generates:
//   * a private `mod` that includes the Faust-generated source with the
//     suppression attrs Faust output requires;
//   * a `<short>_small_signal` test (1 kHz / amp 0.5, fully inside
//     [-xmax, xmax]);
//   * a `<short>_large_signal` test (200 Hz / amp 20, exercises the
//     ymin/ymax saturation arms in dsp/hk_adnl.lib).
//
// The expected fixtures are produced by `tools/gen_fixtures.py` from the
// same `gen_adnl_table(kbias, b, type_b, kloop)` parameters that
// `tools/gen_5e3_tables.py` writes into `dsp/5e3_tables.lib`, so a
// successful run also covers the table generator.
macro_rules! adnl_stage_test {
    ($mod_name:ident, $struct_name:ident, $small:ident, $large:ident, $short:literal) => {
        mod $mod_name {
            #![allow(
                non_snake_case,
                non_camel_case_types,
                non_upper_case_globals,
                dead_code,
                unused_mut,
                unused_variables,
                unused_parens,
                clippy::all
            )]
            use super::*;
            include!(concat!(env!("OUT_DIR"), "/", stringify!($mod_name), ".rs"));
        }

        #[test]
        fn $small() {
            use $mod_name::$struct_name as Dsp;

            let input: Vec<f32> = read_f32_bin("tests/fixtures/sine_1k_amp05_48k_4800.f32");
            let expected: Vec<f32> =
                read_f32_bin(&format!("tests/fixtures/adnl_{}_sine05_48k.f32", $short));

            let mut dsp = Dsp::new();
            dsp.init(48_000);
            dsp.instance_clear();

            let output = run_siso(&mut dsp, &input);
            let report = compare(&output, &expected);
            println!(
                "[adnl {} small] max_abs={:.3e}  rms={:.3e}  n={}",
                $short, report.max_abs, report.rms, report.n
            );
            report.assert_within(1e-3, 1e-4, stringify!($small));
        }

        #[test]
        fn $large() {
            use $mod_name::$struct_name as Dsp;

            let input: Vec<f32> = read_f32_bin("tests/fixtures/sine_200_amp20_48k_4800.f32");
            let expected: Vec<f32> =
                read_f32_bin(&format!("tests/fixtures/adnl_{}_sine20_48k.f32", $short));

            let mut dsp = Dsp::new();
            dsp.init(48_000);
            dsp.instance_clear();

            let output = run_siso(&mut dsp, &input);
            let report = compare(&output, &expected);
            println!(
                "[adnl {} large] max_abs={:.3e}  rms={:.3e}  n={}",
                $short, report.max_abs, report.rms, report.n
            );
            report.assert_within(1e-3, 1e-4, stringify!($large));
        }
    };
}

adnl_stage_test!(
    test_adnl_t1_12ax7,
    test_adnl_t1_12ax7,
    adnl_t1_12ax7_small_signal,
    adnl_t1_12ax7_large_signal,
    "t1_12ax7"
);

adnl_stage_test!(
    test_adnl_t2_12ax7,
    test_adnl_t2_12ax7,
    adnl_t2_12ax7_small_signal,
    adnl_t2_12ax7_large_signal,
    "t2_12ax7"
);

adnl_stage_test!(
    test_adnl_t3_cd,
    test_adnl_t3_cd,
    adnl_t3_cd_small_signal,
    adnl_t3_cd_large_signal,
    "t3_cd"
);

adnl_stage_test!(
    test_adnl_t4_6v6,
    test_adnl_t4_6v6,
    adnl_t4_6v6_small_signal,
    adnl_t4_6v6_large_signal,
    "t4_6v6"
);

adnl_stage_test!(
    test_adnl_t5_6v6,
    test_adnl_t5_6v6,
    adnl_t5_6v6_small_signal,
    adnl_t5_6v6_large_signal,
    "t5_6v6"
);

// ---------------------------------------------------------------------------
// Filters — flt_ii1_lp / flt_ii1_hp / flt_sv2_tst
// ---------------------------------------------------------------------------
//
// Each harness DSP freezes one filter at the operating point nilamp.dsp
// uses on the chain output (dsp/nilamp.dsp:37) and runs it on the shared
// 1 kHz / amp 0.5 sine.  Oracle: keller_oracle.flt_*_block.
macro_rules! filter_test {
    ($mod_name:ident, $struct_name:ident, $test_fn:ident, $fixture:literal, $tag:literal) => {
        mod $mod_name {
            #![allow(
                non_snake_case,
                non_camel_case_types,
                non_upper_case_globals,
                dead_code,
                unused_mut,
                unused_variables,
                unused_parens,
                clippy::all
            )]
            use super::*;
            include!(concat!(env!("OUT_DIR"), "/", stringify!($mod_name), ".rs"));
        }

        #[test]
        fn $test_fn() {
            use $mod_name::$struct_name as Dsp;

            let input: Vec<f32> = read_f32_bin("tests/fixtures/sine_1k_amp05_48k_4800.f32");
            let expected: Vec<f32> = read_f32_bin(concat!("tests/fixtures/", $fixture));

            let mut dsp = Dsp::new();
            dsp.init(48_000);
            dsp.instance_clear();

            let output = run_siso(&mut dsp, &input);
            let report = compare(&output, &expected);
            println!(
                "[filter {}] max_abs={:.3e}  rms={:.3e}  n={}",
                $tag, report.max_abs, report.rms, report.n
            );
            report.assert_within(1e-3, 1e-4, stringify!($test_fn));
        }
    };
}

filter_test!(
    test_filter_lp,
    test_filter_lp,
    filter_lp_matches_oracle,
    "filter_lp_8800_sine05_48k.f32",
    "ii1_lp_8800"
);

filter_test!(
    test_filter_hp,
    test_filter_hp,
    filter_hp_matches_oracle,
    "filter_hp_10_sine05_48k.f32",
    "ii1_hp_10"
);

filter_test!(
    test_filter_svf_tst,
    test_filter_svf_tst,
    filter_svf_tst_matches_oracle,
    "filter_svf_tst_sine05_48k.f32",
    "sv2_tst"
);

// ---------------------------------------------------------------------------
// Composite tube stages — full pipeline (ADNL + PKD + advk + state)
// ---------------------------------------------------------------------------
//
// These pin the full per-stage Faust signal path (dsp/hk_tube.lib's
// tube_ck_simple / tube_cd) against TubeCk / TubeCd in keller_oracle.py.
// Each harness hard-codes dvs=0 and uses a single representative stage
// (T2 for CK because kpk>0 + kfb>0; T3 for CD as the only cathodyne in
// 5E3).  Closed-loop coverage is deferred to the nilamp.dsp end-to-end
// test (gated behind NILAMP_BUILD_TOPLEVEL).
//
// Each macro emits the include-with-allow boilerplate and pins all
// outputs the harness produces (2 for tube_ck, 3 for tube_cd).

macro_rules! tube_test_module {
    ($mod_name:ident) => {
        mod $mod_name {
            #![allow(
                non_snake_case,
                non_camel_case_types,
                non_upper_case_globals,
                dead_code,
                unused_mut,
                unused_variables,
                unused_parens,
                clippy::all
            )]
            use super::*;
            include!(concat!(env!("OUT_DIR"), "/", stringify!($mod_name), ".rs"));
        }
    };
}

tube_test_module!(test_tube_ck);
tube_test_module!(test_tube_ck_t5);

#[test]
fn tube_ck_t2_matches_oracle() {
    use test_tube_ck::test_tube_ck as Dsp;

    let input: Vec<f32> = read_f32_bin("tests/fixtures/sine_1k_amp05_48k_4800.f32");
    let exp_v: Vec<f32> = read_f32_bin("tests/fixtures/tube_ck_t2_v_sine05_48k.f32");
    let exp_dia: Vec<f32> = read_f32_bin("tests/fixtures/tube_ck_t2_dia_sine05_48k.f32");

    let mut dsp = Dsp::new();
    dsp.init(48_000);
    dsp.instance_clear();
    assert_eq!(
        dsp.get_num_outputs(),
        2,
        "tube_ck harness must emit (v_out, dia)"
    );

    let outputs = run_simo(&mut dsp, &input);
    let r_v = compare(&outputs[0], &exp_v);
    let r_dia = compare(&outputs[1], &exp_dia);
    println!(
        "[tube_ck T2] v: max_abs={:.3e} rms={:.3e}  dia: max_abs={:.3e} rms={:.3e}",
        r_v.max_abs, r_v.rms, r_dia.max_abs, r_dia.rms
    );
    // v_out is plate voltage in volts (peak ~150V); dia in amps (~mA).
    // Tolerances scaled accordingly.  RMS floor relative to signal RMS
    // gives roughly -60 dB which matches the project's "close enough"
    // policy.
    r_v.assert_within(0.5, 5e-2, "tube_ck_t2_v");
    r_dia.assert_within(5e-6, 5e-7, "tube_ck_t2_dia");
}

#[test]
fn tube_ck_t5_matches_oracle() {
    use test_tube_ck_t5::test_tube_ck_t5 as Dsp;

    let input: Vec<f32> = read_f32_bin("tests/fixtures/sine_1k_amp05_48k_4800.f32");
    let exp_v: Vec<f32> = read_f32_bin("tests/fixtures/tube_ck_t5_v_sine05_48k.f32");
    let exp_dia: Vec<f32> = read_f32_bin("tests/fixtures/tube_ck_t5_dia_sine05_48k.f32");

    let mut dsp = Dsp::new();
    dsp.init(48_000);
    dsp.instance_clear();
    assert_eq!(
        dsp.get_num_outputs(),
        2,
        "tube_ck T5 harness must emit (v_out, dia)"
    );

    let outputs = run_simo(&mut dsp, &input);
    let r_v = compare(&outputs[0], &exp_v);
    let r_dia = compare(&outputs[1], &exp_dia);
    println!(
        "[tube_ck T5] v: max_abs={:.3e} rms={:.3e}  dia: max_abs={:.3e} rms={:.3e}",
        r_v.max_abs, r_v.rms, r_dia.max_abs, r_dia.rms
    );
    r_v.assert_within(0.5, 5e-2, "tube_ck_t5_v");
    // T5's faster PKD and larger 6V6 current scale put dia at a slightly
    // higher float32 oracle/Faust precision floor than the small-signal T2
    // CK harness.  This is still ~-59 dB RMS relative to dia RMS.
    r_dia.assert_within(7e-5, 2e-6, "tube_ck_t5_dia");
}

tube_test_module!(test_power_pair_t5);

#[test]
fn power_pair_t5_matches_oracle() {
    use test_power_pair_t5::test_power_pair_t5 as Dsp;

    let t3_v: Vec<f32> = read_f32_bin("tests/fixtures/power_pair_t3_v_48k.f32");
    let t3_vk: Vec<f32> = read_f32_bin("tests/fixtures/power_pair_t3_vk_48k.f32");
    let exp_t4_v: Vec<f32> = read_f32_bin("tests/fixtures/power_pair_t4_v_48k.f32");
    let exp_t5_v: Vec<f32> = read_f32_bin("tests/fixtures/power_pair_t5_v_48k.f32");
    let exp_post: Vec<f32> = read_f32_bin("tests/fixtures/power_pair_post_pp_48k.f32");
    let exp_dia: Vec<f32> = read_f32_bin("tests/fixtures/power_pair_total_dia_48k.f32");

    let mut dsp = Dsp::new();
    dsp.init(48_000);
    dsp.instance_clear();
    assert_eq!(
        dsp.get_num_inputs(),
        2,
        "power-pair harness must consume T3 plate/cathode taps"
    );
    assert_eq!(
        dsp.get_num_outputs(),
        4,
        "power-pair harness must emit four diagnostic signals"
    );

    let outputs = run_mimo(&mut dsp, &[&t3_v, &t3_vk]);
    let r_t4 = compare(&outputs[0], &exp_t4_v);
    let r_t5 = compare(&outputs[1], &exp_t5_v);
    let r_post = compare(&outputs[2], &exp_post);
    let r_dia = compare(&outputs[3], &exp_dia);
    println!(
        "[power-pair] t4: max_abs={:.3e} rms={:.3e}  t5: max_abs={:.3e} rms={:.3e}  post: max_abs={:.3e} rms={:.3e}  dia: max_abs={:.3e} rms={:.3e}",
        r_t4.max_abs, r_t4.rms, r_t5.max_abs, r_t5.rms,
        r_post.max_abs, r_post.rms, r_dia.max_abs, r_dia.rms
    );
    r_t4.assert_within(0.5, 5e-2, "power_pair_t4_v");
    r_t5.assert_within(0.5, 5e-2, "power_pair_t5_v");
    r_post.assert_within(0.75, 7.5e-2, "power_pair_post_pp");
    // total_dia sums two independent 6V6 current paths, so it inherits the
    // per-power-tube precision floor from both branches.
    r_dia.assert_within(2e-4, 2e-5, "power_pair_total_dia");
}

tube_test_module!(test_tube_cd);

#[test]
fn tube_cd_t3_matches_oracle() {
    use test_tube_cd::test_tube_cd as Dsp;

    let input: Vec<f32> = read_f32_bin("tests/fixtures/sine_1k_amp05_48k_4800.f32");
    let exp_v: Vec<f32> = read_f32_bin("tests/fixtures/tube_cd_t3_v_sine05_48k.f32");
    let exp_vk: Vec<f32> = read_f32_bin("tests/fixtures/tube_cd_t3_vk_sine05_48k.f32");
    let exp_dia: Vec<f32> = read_f32_bin("tests/fixtures/tube_cd_t3_dia_sine05_48k.f32");

    let mut dsp = Dsp::new();
    dsp.init(48_000);
    dsp.instance_clear();
    assert_eq!(
        dsp.get_num_outputs(),
        3,
        "tube_cd harness must emit (v, vk, dia)"
    );

    let outputs = run_simo(&mut dsp, &input);
    let r_v = compare(&outputs[0], &exp_v);
    let r_vk = compare(&outputs[1], &exp_vk);
    let r_dia = compare(&outputs[2], &exp_dia);
    println!(
        "[tube_cd T3] v: max_abs={:.3e} rms={:.3e}  vk: max_abs={:.3e} rms={:.3e}  dia: max_abs={:.3e} rms={:.3e}",
        r_v.max_abs, r_v.rms, r_vk.max_abs, r_vk.rms, r_dia.max_abs, r_dia.rms
    );
    r_v.assert_within(0.5, 5e-2, "tube_cd_t3_v");
    r_vk.assert_within(0.5, 5e-2, "tube_cd_t3_vk");
    r_dia.assert_within(5e-6, 5e-7, "tube_cd_t3_dia");
}

// ---------------------------------------------------------------------------
// DZ-variant tube stages — Dempwolf-Zölzer ECC83 + load-line ADNL tables
// ---------------------------------------------------------------------------
//
// Same harness shape as tube_ck_t2 / tube_cd_t3 above, but the ADNL
// table is the per-stage `*_table_dz` variant emitted by
// gen_5e3_tables.py (load-line solved against Dempwolf-Zölzer ECC83
// equations, clipped to the GLF saturation range).  These pin the
// full DZ generator + Faust wiring path against the oracle's
// adnl_set_dz_ck / adnl_set_dz_cd.
//
// dvs is hard-coded to 0 (open-loop), and the same tolerances are
// used as the GLF variants — DZ tables share the file format,
// xmax/dx, and ymin/ymax saturation window with GLF, so the only
// relevant numerical difference is the curve coefficients themselves.

tube_test_module!(test_tube_ck_t2_dz);

#[test]
fn tube_ck_t2_dz_matches_oracle() {
    use test_tube_ck_t2_dz::test_tube_ck_t2_dz as Dsp;

    let input: Vec<f32> = read_f32_bin("tests/fixtures/sine_1k_amp05_48k_4800.f32");
    let exp_v: Vec<f32> = read_f32_bin("tests/fixtures/tube_ck_t2_dz_v_sine05_48k.f32");
    let exp_dia: Vec<f32> = read_f32_bin("tests/fixtures/tube_ck_t2_dz_dia_sine05_48k.f32");

    let mut dsp = Dsp::new();
    dsp.init(48_000);
    dsp.instance_clear();
    assert_eq!(
        dsp.get_num_outputs(),
        2,
        "tube_ck_dz harness must emit (v_out, dia)"
    );

    let outputs = run_simo(&mut dsp, &input);
    let r_v = compare(&outputs[0], &exp_v);
    let r_dia = compare(&outputs[1], &exp_dia);
    println!(
        "[tube_ck T2 DZ] v: max_abs={:.3e} rms={:.3e}  dia: max_abs={:.3e} rms={:.3e}",
        r_v.max_abs, r_v.rms, r_dia.max_abs, r_dia.rms
    );
    r_v.assert_within(0.5, 5e-2, "tube_ck_t2_dz_v");
    r_dia.assert_within(5e-6, 5e-7, "tube_ck_t2_dz_dia");
}

tube_test_module!(test_tube_cd_t3_dz);

#[test]
fn tube_cd_t3_dz_matches_oracle() {
    use test_tube_cd_t3_dz::test_tube_cd_t3_dz as Dsp;

    let input: Vec<f32> = read_f32_bin("tests/fixtures/sine_1k_amp05_48k_4800.f32");
    let exp_v: Vec<f32> = read_f32_bin("tests/fixtures/tube_cd_t3_dz_v_sine05_48k.f32");
    let exp_vk: Vec<f32> = read_f32_bin("tests/fixtures/tube_cd_t3_dz_vk_sine05_48k.f32");
    let exp_dia: Vec<f32> = read_f32_bin("tests/fixtures/tube_cd_t3_dz_dia_sine05_48k.f32");

    let mut dsp = Dsp::new();
    dsp.init(48_000);
    dsp.instance_clear();
    assert_eq!(
        dsp.get_num_outputs(),
        3,
        "tube_cd_dz harness must emit (v, vk, dia)"
    );

    let outputs = run_simo(&mut dsp, &input);
    let r_v = compare(&outputs[0], &exp_v);
    let r_vk = compare(&outputs[1], &exp_vk);
    let r_dia = compare(&outputs[2], &exp_dia);
    println!(
        "[tube_cd T3 DZ] v: max_abs={:.3e} rms={:.3e}  vk: max_abs={:.3e} rms={:.3e}  dia: max_abs={:.3e} rms={:.3e}",
        r_v.max_abs, r_v.rms, r_vk.max_abs, r_vk.rms, r_dia.max_abs, r_dia.rms
    );
    // The cathodyne DZ curve is essentially step-shaped (saturates within
    // a single 0.02-wide segment around x=0), which is at the precision
    // floor of the cubic-fit table format.  A signal sweeping through
    // the transition each cycle produces a localized error spike at the
    // zero-crossing — capped at <0.25 V on a ~30 V waveform (~1% rel),
    // but nudges the RMS above the standard 5e-2 tolerance, so we
    // double the RMS limit for the DZ variants only.  The dia output
    // (which gates the full PSS sag loop downstream) stays inside the
    // baseline tolerance.
    r_v.assert_within(0.5, 1e-1, "tube_cd_t3_dz_v");
    r_vk.assert_within(0.5, 1e-1, "tube_cd_t3_dz_vk");
    r_dia.assert_within(5e-6, 2e-6, "tube_cd_t3_dz_dia");
}

tube_test_module!(test_pss);

#[test]
fn pss_matches_oracle() {
    use test_pss::test_pss as Dsp;

    let input: Vec<f32> = read_f32_bin("tests/fixtures/sine_1k_amp05_48k_4800.f32");
    let exp_dvs: Vec<f32> = read_f32_bin("tests/fixtures/pss_dvs_sine05_48k.f32");
    let exp_s: Vec<f32> = read_f32_bin("tests/fixtures/pss_s_sine05_48k.f32");

    let mut dsp = Dsp::new();
    dsp.init(48_000);
    dsp.instance_clear();
    assert_eq!(
        dsp.get_num_outputs(),
        2,
        "pss harness must emit (dvs_out, s)"
    );

    let outputs = run_simo(&mut dsp, &input);
    let r_dvs = compare(&outputs[0], &exp_dvs);
    let r_s = compare(&outputs[1], &exp_s);
    println!(
        "[pss] dvs: max_abs={:.3e} rms={:.3e}  s: max_abs={:.3e} rms={:.3e}",
        r_dvs.max_abs, r_dvs.rms, r_s.max_abs, r_s.rms
    );
    // PSS is purely linear (two LP filters); behaviour matches the
    // filter tests' float-precision band.
    r_dvs.assert_within(1e-2, 1e-3, "pss_dvs");
    r_s.assert_within(1e-3, 1e-4, "pss_s");
}
