#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Sample REAPER Performance Meter CPU/FX CPU while the Lua scenario driver runs."""
from __future__ import annotations

import argparse
import csv
import json
import os
import re
import statistics
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


HERE = Path(__file__).resolve().parent
DRIVER = HERE / "run_reaper_perf_scenarios.lua"

CPU_RE = re.compile(r"\bCPU:\s*([0-9]+(?:\.[0-9]+)?)%")
FX_RE = re.compile(r"(?:\bFX CPU|\b[0-9]+\s+FX|\bFX):\s*([0-9]+(?:\.[0-9]+)?)%")
FX_COUNT_RE = re.compile(r"\b([0-9]+)\s+FX:")
MEDIA_RE = re.compile(r"\bMedia\s+([0-9]+(?:\.[0-9]+)?)%")

OPEN_PERF_METER_SCRIPT = """
tell application "System Events" to tell process "REAPER"
  if not (exists window "Performance Meter") then
    click menu item "Performance Meter" of menu "View" of menu bar 1
  end if
end tell
"""

READ_PERF_METER_SCRIPT = """
tell application "System Events" to tell process "REAPER"
  if not (exists window "Performance Meter") then
    return "__NILAMP_NO_PERF_WINDOW__"
  end if
  set AppleScript's text item delimiters to linefeed
  set vals to value of static texts of window "Performance Meter"
  return vals as text
end tell
"""


def default_temp_path(name: str) -> Path:
    temp = os.environ.get("TMPDIR") or os.environ.get("TEMP") or os.environ.get("TMP") or "/tmp"
    return Path(temp) / name


def default_marker_path() -> Path:
    return default_temp_path("nilamp_reaper_perf_markers.jsonl")


def default_config_path() -> Path:
    return default_temp_path("nilamp_reaper_perf_config.lua")


def lua_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_lua_config(path: Path, args: argparse.Namespace) -> None:
    lines = [
        "-- Auto-generated by measure_reaper_perf_meter.py; safe to delete.",
        "return {",
        f"  marker_path = {lua_str(str(args.marker_path))},",
        f"  scenario_seconds = {args.scenario_seconds:.9f},",
        f"  settle_seconds = {args.settle_seconds:.9f},",
        f"  repeats = {args.repeats},",
        f"  surfaces = {lua_str(args.surfaces)},",
        "}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def run_osascript(script: str) -> str:
    cmd = ["osascript"]
    for line in script.strip().splitlines():
        cmd.extend(["-e", line])
    proc = subprocess.run(
        cmd,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip() or f"osascript exited {proc.returncode}")
    return proc.stdout


def ensure_perf_meter() -> None:
    run_osascript(OPEN_PERF_METER_SCRIPT)


def read_perf_meter_text() -> str:
    return run_osascript(READ_PERF_METER_SCRIPT)


def parse_perf_meter(text: str) -> dict[str, Any]:
    cpu = CPU_RE.search(text)
    fx = FX_RE.search(text)
    fx_count = FX_COUNT_RE.search(text)
    media = MEDIA_RE.search(text)
    return {
        "reaper_cpu_pct": float(cpu.group(1)) if cpu else None,
        "reaper_fx_cpu_pct": float(fx.group(1)) if fx else None,
        "reaper_fx_count": int(fx_count.group(1)) if fx_count else None,
        "reaper_media_cpu_pct": float(media.group(1)) if media else None,
        "perf_meter_text": text.strip(),
    }


def read_new_markers(path: Path, line_count: int) -> tuple[list[dict[str, Any]], int]:
    if not path.exists():
        return [], line_count
    lines = path.read_text(encoding="utf-8").splitlines()
    markers: list[dict[str, Any]] = []
    for line in lines[line_count:]:
        if not line.strip():
            continue
        try:
            markers.append(json.loads(line))
        except json.JSONDecodeError:
            print(f"warning: ignoring malformed marker line: {line}", file=sys.stderr)
    return markers, len(lines)


def percentile(values: list[float], pct: float) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    if len(ordered) == 1:
        return ordered[0]
    rank = (pct / 100.0) * (len(ordered) - 1)
    lo = int(rank)
    hi = min(lo + 1, len(ordered) - 1)
    weight = rank - lo
    return ordered[lo] * (1.0 - weight) + ordered[hi] * weight


def mean(values: list[float]) -> float | None:
    return statistics.fmean(values) if values else None


def write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    fieldnames: list[str] = []
    for row in rows:
        for key in row:
            if key not in fieldnames:
                fieldnames.append(key)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def metric_summary(values: list[float], prefix: str) -> dict[str, Any]:
    return {
        f"mean_{prefix}": mean(values),
        f"median_{prefix}": percentile(values, 50),
        f"p95_{prefix}": percentile(values, 95),
        f"max_{prefix}": max(values) if values else None,
    }


def summarize(samples: list[dict[str, Any]], markers: list[dict[str, Any]],
              warmup_trim_s: float, cooldown_trim_s: float) -> list[dict[str, Any]]:
    starts: dict[tuple[str, int], dict[str, Any]] = {}
    intervals: list[dict[str, Any]] = []
    for marker in markers:
        key = (str(marker.get("scenario", "")), int(marker.get("run") or 0))
        if marker.get("event") == "start":
            starts[key] = marker
        elif marker.get("event") == "end" and key in starts:
            start = starts.pop(key)
            intervals.append({
                "scenario": marker.get("scenario", ""),
                "surface": marker.get("surface", ""),
                "editor": marker.get("editor", ""),
                "run": int(marker.get("run") or 0),
                "fx_name": marker.get("fx_name", ""),
                "start_elapsed_s": start["observed_elapsed_s"],
                "end_elapsed_s": marker["observed_elapsed_s"],
            })

    rows: list[dict[str, Any]] = []
    aggregate_values: dict[str, dict[str, Any]] = {}
    for interval in intervals:
        start_s = float(interval["start_elapsed_s"]) + warmup_trim_s
        end_s = float(interval["end_elapsed_s"]) - cooldown_trim_s
        window = [s for s in samples if start_s <= float(s["elapsed_s"]) <= end_s]
        cpu_values = [float(s["reaper_cpu_pct"]) for s in window if s.get("reaper_cpu_pct") is not None]
        fx_values = [float(s["reaper_fx_cpu_pct"]) for s in window if s.get("reaper_fx_cpu_pct") is not None]
        row = {
            "row_type": "run",
            **interval,
            "samples": len(window),
            "warmup_trim_s": warmup_trim_s,
            "cooldown_trim_s": cooldown_trim_s,
            **metric_summary(cpu_values, "reaper_cpu_pct"),
            **metric_summary(fx_values, "reaper_fx_cpu_pct"),
        }
        rows.append(row)

        scenario = str(interval["scenario"])
        agg = aggregate_values.setdefault(scenario, {
            "surface": interval["surface"],
            "editor": interval["editor"],
            "fx_name": interval["fx_name"],
            "cpu_values": [],
            "fx_values": [],
        })
        agg["cpu_values"].extend(cpu_values)
        agg["fx_values"].extend(fx_values)

    for scenario in sorted(aggregate_values):
        agg = aggregate_values[scenario]
        rows.append({
            "row_type": "aggregate",
            "scenario": scenario,
            "surface": agg["surface"],
            "editor": agg["editor"],
            "run": 0,
            "fx_name": agg["fx_name"],
            "samples": len(agg["cpu_values"]),
            "start_elapsed_s": "",
            "end_elapsed_s": "",
            "warmup_trim_s": warmup_trim_s,
            "cooldown_trim_s": cooldown_trim_s,
            **metric_summary(agg["cpu_values"], "reaper_cpu_pct"),
            **metric_summary(agg["fx_values"], "reaper_fx_cpu_pct"),
        })
    return rows


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--marker-path", type=Path, default=default_marker_path())
    ap.add_argument("--config-path", type=Path, default=default_config_path())
    ap.add_argument("--out-dir", type=Path, default=Path("dist/reaper-perf"))
    ap.add_argument("--poll-ms", type=int, default=1000)
    ap.add_argument("--timeout-seconds", type=float, default=900.0)
    ap.add_argument("--scenario-seconds", type=float, default=15.0)
    ap.add_argument("--settle-seconds", type=float, default=3.0)
    ap.add_argument("--repeats", type=int, default=3)
    ap.add_argument("--surfaces", default="nilamp_clap,nilamp_vst3")
    ap.add_argument("--warmup-trim-seconds", type=float, default=2.0)
    ap.add_argument("--cooldown-trim-seconds", type=float, default=1.0)
    ap.add_argument("--keep-existing-markers", action="store_true")
    args = ap.parse_args()

    if args.poll_ms <= 0:
        ap.error("--poll-ms must be positive")
    if args.repeats <= 0:
        ap.error("--repeats must be positive")
    args.out_dir.mkdir(parents=True, exist_ok=True)
    args.config_path.parent.mkdir(parents=True, exist_ok=True)
    args.marker_path.parent.mkdir(parents=True, exist_ok=True)
    if not args.keep_existing_markers:
        args.marker_path.unlink(missing_ok=True)
    args.marker_path.touch(exist_ok=True)
    write_lua_config(args.config_path, args)
    ensure_perf_meter()

    stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    raw_csv = args.out_dir / f"reaper-perf-meter-samples-{stamp}.csv"
    raw_json = args.out_dir / f"reaper-perf-meter-samples-{stamp}.json"
    marker_json = args.out_dir / f"reaper-perf-meter-markers-{stamp}.json"
    summary_csv = args.out_dir / f"reaper-perf-meter-summary-{stamp}.csv"
    summary_json = args.out_dir / f"reaper-perf-meter-summary-{stamp}.json"

    print(f"Sampling REAPER Performance Meter every {args.poll_ms} ms.")
    print(f"Config file: {args.config_path}")
    print(f"Marker file: {args.marker_path}")
    print(f"Run {DRIVER} inside REAPER now.")

    samples: list[dict[str, Any]] = []
    markers: list[dict[str, Any]] = []
    start_mono = time.monotonic()
    line_count = 0
    done = False
    while not done:
        time.sleep(args.poll_ms / 1000.0)
        elapsed_s = time.monotonic() - start_mono
        if elapsed_s > args.timeout_seconds:
            raise RuntimeError(f"timed out after {args.timeout_seconds:g} seconds waiting for done marker")

        text = read_perf_meter_text()
        if "__NILAMP_NO_PERF_WINDOW__" in text:
            raise RuntimeError("REAPER Performance Meter window is not open")
        sample = parse_perf_meter(text)
        sample.update({
            "time_utc": datetime.now(timezone.utc).isoformat(),
            "elapsed_s": elapsed_s,
        })
        samples.append(sample)

        new_markers, line_count = read_new_markers(args.marker_path, line_count)
        for marker in new_markers:
            marker["observed_utc"] = sample["time_utc"]
            marker["observed_elapsed_s"] = elapsed_s
            markers.append(marker)
            if marker.get("event") == "done":
                done = True

    summary = summarize(samples, markers, args.warmup_trim_seconds, args.cooldown_trim_seconds)
    write_csv(raw_csv, samples)
    raw_json.write_text(json.dumps(samples, indent=2), encoding="utf-8")
    marker_json.write_text(json.dumps(markers, indent=2), encoding="utf-8")
    write_csv(summary_csv, summary)
    summary_json.write_text(json.dumps(summary, indent=2), encoding="utf-8")

    print()
    print("Aggregate scenario summary from REAPER Performance Meter:")
    for row in summary:
        if row["row_type"] != "aggregate":
            continue
        cpu = row["median_reaper_cpu_pct"]
        fx = row["median_reaper_fx_cpu_pct"]
        cpu_s = f"{cpu:.3f}%" if cpu is not None else "n/a"
        fx_s = f"{fx:.3f}%" if fx is not None else "n/a"
        print(f"{row['scenario']:<28} samples={row['samples']:<4} CPU={cpu_s} FX CPU={fx_s}")
    print("Wrote:")
    for path in (summary_csv, summary_json, raw_csv, raw_json, marker_json):
        print(f"  {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
