#!/usr/bin/env python3
"""Generate C font asset data from a binary font file."""

from __future__ import annotations

import argparse
from pathlib import Path


def guard_name(symbol: str) -> str:
    return f"{symbol.upper()}_H"


def render_header(symbol: str) -> str:
    guard = guard_name(symbol)
    return (
        "/* SPDX-License-Identifier: OFL-1.1 */\n"
        "/* Generated by tools/gen_font_asset.py; do not hand-edit. */\n"
        f"#ifndef {guard}\n"
        f"#define {guard}\n\n"
        "#include <stddef.h>\n\n"
        f"extern const unsigned char {symbol}_data[];\n"
        f"extern const size_t {symbol}_size;\n\n"
        f"#endif /* {guard} */\n"
    )


def render_source(symbol: str, header_name: str, data: bytes) -> str:
    lines = [
        "/* SPDX-License-Identifier: OFL-1.1 */",
        "/* Generated by tools/gen_font_asset.py; do not hand-edit. */",
        f'#include "{header_name}"',
        "",
        f"const unsigned char {symbol}_data[] = {{",
    ]
    for offset in range(0, len(data), 12):
        chunk = data[offset:offset + 12]
        values = ", ".join(f"0x{byte:02x}" for byte in chunk)
        lines.append(f"    {values},")
    lines.extend([
        "};",
        f"const size_t {symbol}_size = sizeof({symbol}_data);",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--symbol", required=True)
    parser.add_argument("--header", required=True, type=Path)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("font", type=Path)
    args = parser.parse_args()

    data = args.font.read_bytes()
    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.source.parent.mkdir(parents=True, exist_ok=True)
    args.header.write_text(render_header(args.symbol))
    args.source.write_text(render_source(args.symbol, args.header.name, data))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
